jd-opensource/drip-table

packages/drip-table-generator/package.json
packages/drip-table-generator/src/drip-table-generator.tsx
packages/drip-table-generator/src/wrapper.tsx

release: drip-table-generator 1.0.2

release DripTableGenerator

---

README.md
README.zh-CN.md
package.json
packages/drip-table-generator/DEVELOP.md
packages/drip-table-generator/DEVELOP.zh-CN.md
packages/drip-table-generator/README.md
packages/drip-table-generator/README.zh-CN.md
packages/drip-table-generator/src/drip-table-generator.tsx
packages/drip-table-generator/src/layout/tool-layout/index.tsx
packages/drip-table-generator/src/store/index.ts
packages/drip-table-generator/src/table-components/text.ts
packages/drip-table-generator/src/typing.ts

fix bug of generator type errors, change readme and unite dataIndex ui type

Drip Table Generator type fix and readme change

---

docs/drip-table/guide/basic-demo.md

update basic sample content

---

DEVELOP.md
DEVELOP.zh-CN.md
docs/drip-table/guide/basic-demo.md

feat: DEVELOP-Translation jump

feat: DEVELOP-Translation jump

---

docs/drip-table-generator/preview/sample.module.less
docs/drip-table-generator/preview/sample.tsx
packages/drip-table-generator/.fatherrc.ts
packages/drip-table-generator/src/context.ts
packages/drip-table-generator/src/drip-table-generator.tsx
packages/drip-table-generator/src/layout/attribute-layout/index.tsx
packages/drip-table-generator/src/layout/editable-table/index.tsx
packages/drip-table-generator/src/layout/preview-table/index.tsx
packages/drip-table-generator/src/layout/tool-layout/index.tsx
packages/drip-table-generator/src/store/index.ts
packages/drip-table-generator/src/typing.ts
packages/drip-table-generator/src/wrapper.tsx
packages/drip-table/.fatherrc.ts

feat: generator add function of getDataSource from ref
build: bind plugin eslint to generator

feat: generator add function of getDataSource from ref

---

README.md
README.zh-CN.md

docs(readme): add gitter link

---

docs/drip-table-generator/preview/component-settings.ts
packages/drip-table-generator/src/components/CustomForm/index.tsx
packages/drip-table-generator/src/index.module.less
packages/drip-table-generator/src/layout/attribute-layout/index.module.less
packages/drip-table-generator/src/layout/attribute-layout/index.tsx
packages/drip-table-generator/src/layout/component-layout/index.module.less
packages/drip-table-generator/src/layout/component-layout/index.tsx
packages/drip-table-generator/src/wrapper.tsx

feat: attribute form add render html
feat: update generator styles

feat: attribute form add render html

---

docs/index.css
package.json

fix: remove dark theme button

---

docs/drip-table-generator/preview/TextComponent.tsx
docs/drip-table-generator/preview/component-settings.ts
docs/drip-table-generator/preview/sample.tsx
package.json
packages/drip-table/src/drip-table/index.tsx

refactor: restore generator sample to formmat style

fix: column head description support html string

---

packages/drip-table-generator/src/components/CustomForm/components/ArrayComponent/index.tsx
packages/drip-table-generator/src/components/CustomForm/index.tsx
packages/drip-table-generator/src/table-components/picture.ts
packages/drip-table-generator/src/table-components/tag.ts
packages/drip-table-generator/src/table-components/text.ts
packages/drip-table/src/drip-table/components/text/index.tsx

feat: dataIndex support inputing string array

---

docs/demo-data.ts
docs/drip-table/sample/sample.tsx
packages/drip-table/src/drip-table/index.module.css
packages/drip-table/src/drip-table/index.tsx
packages/drip-table/src/types/driver/table.ts
packages/drip-table/src/types/index.ts

feat: support drip table expandable rows

feat: support drip table expandable rows

---

docs/demo-data.ts
docs/drip-table/functions/index.md
docs/drip-table/sample/sample.tsx
packages/drip-table-generator/src/layout/attribute-layout/index.tsx
packages/drip-table-generator/src/layout/configs.ts
packages/drip-table-generator/src/typing.ts
packages/drip-table/src/drip-table/components/component.ts
packages/drip-table/src/drip-table/header/index.tsx
packages/drip-table/src/drip-table/index.tsx
packages/drip-table/src/types/driver/component.ts
packages/drip-table/src/types/driver/table.ts
packages/drip-table/src/types/index.ts

Subtable recursive

---

packages/drip-table-generator/src/layout/attribute-layout/index.tsx
packages/drip-table-generator/src/table-components/button.ts
packages/drip-table-generator/src/table-components/configs.ts
packages/drip-table-generator/src/table-components/group.ts
packages/drip-table-generator/src/table-components/links.ts
packages/drip-table-generator/src/table-components/picture.ts
packages/drip-table-generator/src/table-components/render-html-remote.ts
packages/drip-table-generator/src/table-components/render-html.ts
packages/drip-table-generator/src/table-components/rich-text.ts
packages/drip-table-generator/src/table-components/tag.ts
packages/drip-table-generator/src/table-components/text.ts

feat:  add default value of table column header

---

Contact.md
README.md
README.zh-CN.md

docs: add contact

---

packages/drip-table/src/components/built-in/render-html-remote/index.tsx
packages/drip-table/src/components/built-in/render-html/index.tsx
packages/drip-table/src/components/built-in/rich-text/index.tsx

fix: rich-text and render-html bug

---

docs/drip-table/props/sticky.md
docs/drip-table/schema/sticky.md
packages/drip-table/src/layouts/table/index.module.less

bug fix
sticky not working
sticky working
http://test1.drip-table.jd.com/drip-table/schema/sticky
@JDFED/drip-table-reviewers

Fix sticky

---

packages/drip-table-generator/package.json
packages/drip-table-generator/src/components/CustomForm/components/data-translation/index.tsx
packages/drip-table-generator/src/components/CustomForm/components/index.ts
packages/drip-table-generator/src/layouts/attributes-layout/global-configs/index.tsx
packages/drip-table-generator/src/layouts/table-workstation/editable-table/column-header/index.tsx
packages/drip-table-generator/src/layouts/table-workstation/editable-table/column-insert-modal/index.tsx
packages/drip-table-generator/src/table-components/configs.ts

Bug fix
#349
#311
add enum config for enum data translation
https://drip-table.jd.com/demo
@JDFED/drip-table-reviewers

Generator v2.1.1

---

package.json
packages/drip-table/.fatherrc.ts
packages/drip-table/package.json
yarn.lock

drip table build with both minified and unminified files

---

packages/drip-table/package.json
packages/drip-table/src/layouts/table/index.tsx

Fix select all

---

packages/drip-table-generator/README.md
packages/drip-table-generator/README.zh-CN.md

feat: migrate demo image to jss

---

.dumirc.ts
docs/drip-table/schema/columns/filters-max-select.md
docs/drip-table/schema/columns/index.md
packages/drip-table/package.json
packages/drip-table/src/layouts/table/components/header-cell/index.tsx
packages/drip-table/src/types/index.ts
packages/drip-table/src/utils/ajv.ts

Filter max select

---

.dumirc.ts
docs/drip-table/schema/index.md
docs/drip-table/schema/span.md
packages/drip-table/src/layouts/table/index.tsx
packages/drip-table/src/types/index.ts
packages/drip-table/src/utils/ajv.ts

Table Span

---

packages/drip-table/src/layouts/table/index.tsx

fix(drip-table): select all rows should skip non-selectable rows

---

packages/drip-table/src/components/cell-components/date-picker/index.tsx

fix: date picker component dataTranslation not work

---

packages/drip-table/src/components/cell-components/button/index.tsx
packages/drip-table/src/components/cell-components/component.ts
packages/drip-table/src/components/cell-components/group/index.tsx
packages/drip-table/src/components/cell-components/link/index.tsx
packages/drip-table/src/components/cell-components/pop-up-page/index.tsx
packages/drip-table/src/components/cell-components/render-html-remote/index.tsx
packages/drip-table/src/components/cell-components/render-html/index.tsx
packages/drip-table/src/components/cell-components/rich-text/index.tsx
packages/drip-table/src/components/cell-components/select/index.tsx
packages/drip-table/src/components/cell-components/text/index.tsx
packages/drip-table/src/layouts/table/index.tsx

Fix record index

---

DEVELOP.md
DEVELOP.zh-CN.md
packages/drip-table/package.json

release 3.0.0-alpha.9

---

packages/drip-table/package.json
packages/drip-table/src/layouts/table/index.less

Fix sticky z index

---

docs/drip-table/components/button.md
docs/drip-table/components/text.md
packages/drip-table/package.json
packages/drip-table/src/components/cell-components/button/index.tsx
packages/drip-table/src/components/cell-components/link/index.tsx
packages/drip-table/src/components/cell-components/pop-up-page/index.tsx
packages/drip-table/src/components/cell-components/rich-text/index.tsx
packages/drip-table/src/components/cell-components/select/index.tsx
packages/drip-table/src/components/cell-components/text/index.tsx
packages/drip-table/src/components/cell-components/utils.ts

Text tooltip, button popconfirm

---

docs/drip-table/components/index.md
docs/drip-table/components/switch.md
packages/drip-table/package.json
packages/drip-table/src/components/cell-components/index.ts
packages/drip-table/src/components/cell-components/switch/index.tsx
packages/drip-table/src/components/react-components/switch/index.less
packages/drip-table/src/components/react-components/switch/index.tsx
yarn.lock

Switch component

---

packages/drip-table/package.json
packages/drip-table/src/layouts/table/index.tsx

feat(drip-table): optiomize column auto width by only use int value

---

docs/drip-table/components/icon.md
docs/drip-table/components/index.md
packages/drip-table/src/components/cell-components/icon/index.tsx
packages/drip-table/src/components/cell-components/index.ts
packages/drip-table/src/layouts/table/index.tsx
packages/drip-table/src/layouts/table/types.ts
packages/drip-table/src/utils/ajv.ts

Icon component

---

docs/drip-table/components/image.md
docs/drip-table/components/tag.md
packages/drip-table/package.json
packages/drip-table/src/components/cell-components/image/index.less
packages/drip-table/src/components/cell-components/image/index.tsx
packages/drip-table/src/components/cell-components/tag/index.tsx
packages/drip-table/src/components/react-components/image/index.tsx
yarn.lock

Tag max display

---

packages/drip-table/package.json

release: drip-table v3.0.1

---

packages/drip-table-generator/src/layouts/table-workstation/editable-table/components/cell/index.tsx
packages/drip-table/src/components/cell-components/group/index.tsx

feat: add style prop to group component items

---

packages/drip-table-generator/package.json
packages/drip-table/package.json

release: drip-table v3.0.2 drip-table-generator v3.1.3

---

packages/drip-table/src/components/react-components/image/index.less
packages/drip-table/src/components/react-components/image/index.tsx

feat: add icons to image component preview

---

packages/drip-table/package.json
packages/drip-table/src/components/react-components/image/index.less
yarn.lock

feat: upgrade rc-image to v7.x

---

.dumirc.ts
docs/drip-table/schema/bordered.md
docs/drip-table/schema/columns/children.md
docs/drip-table/schema/columns/data-translation.md
docs/drip-table/schema/columns/index.md
packages/drip-table/src/components/cell-components/button/index.tsx
packages/drip-table/src/components/cell-components/icon/index.tsx
packages/drip-table/src/components/cell-components/link/index.tsx
packages/drip-table/src/components/cell-components/pop-up-page/index.tsx
packages/drip-table/src/components/cell-components/render-html-remote/index.tsx
packages/drip-table/src/components/cell-components/render-html/index.tsx
packages/drip-table/src/components/cell-components/rich-text/index.tsx
packages/drip-table/src/components/cell-components/select/index.tsx
packages/drip-table/src/components/cell-components/switch/index.tsx
packages/drip-table/src/components/cell-components/text/index.less
packages/drip-table/src/components/cell-components/text/index.tsx
packages/drip-table/src/components/cell-components/utils.ts
packages/drip-table/src/components/react-components/slot-render/index.tsx
packages/drip-table/src/index.ts
packages/drip-table/src/layouts/index.tsx
packages/drip-table/src/layouts/table/components/header-cell/index.tsx
packages/drip-table/src/layouts/table/index.less
packages/drip-table/src/layouts/table/index.tsx
packages/drip-table/src/types/index.ts
packages/drip-table/src/utils/ajv.ts
packages/drip-table/src/utils/children-like.ts
packages/drip-table/src/wrapper/index.tsx

Release 20240419

---

docs/drip-table/schema/pagination.md
packages/drip-table/src/components/react-components/pagination/index.tsx
packages/drip-table/src/layouts/table/index.tsx
packages/drip-table/src/types/index.ts
packages/drip-table/src/utils/ajv.ts

Pagination styles

---

docs/drip-table/schema/theme.md
packages/drip-table/src/components/react-components/alert/index.less
packages/drip-table/src/components/react-components/button/index.less
packages/drip-table/src/components/react-components/checkbox/index.less
packages/drip-table/src/components/react-components/date-picker/index.less
packages/drip-table/src/components/react-components/dropdown/index.less
packages/drip-table/src/components/react-components/input/index.less
packages/drip-table/src/components/react-components/menu/index.less
packages/drip-table/src/components/react-components/modal/index.less
packages/drip-table/src/components/react-components/pagination/index.less
packages/drip-table/src/components/react-components/select/index.less
packages/drip-table/src/components/react-components/tag/index.less
packages/drip-table/src/components/react-components/tooltip/index.less
packages/drip-table/src/layouts/table/components/header-cell/index.less
packages/drip-table/src/layouts/table/index.less
packages/drip-table/src/types/index.ts
packages/drip-table/src/utils/ajv.ts
packages/drip-table/src/utils/dom.ts

feat: theme add textColor

---

.dumirc.ts
docs/drip-table/api/display-column-keys.md
docs/drip-table/api/index.md
docs/drip-table/api/set-display-column-keys.md
package.json
packages/drip-table-generator/package.json
packages/drip-table/package.json
packages/drip-table/src/wrapper/index.tsx

Set display column keys

---

packages/drip-table-generator/package.json
packages/drip-table/package.json
packages/drip-table/src/wrapper/index.tsx

Display column keys

---

docs/drip-table/components/group.md
packages/drip-table/src/components/cell-components/text/index.less
packages/drip-table/src/components/cell-components/text/index.tsx
packages/drip-table/src/components/react-components/col/index.less

Group text compatible

---

docs/drip-table/components/button.md
docs/drip-table/components/text.md
packages/drip-table/src/components/cell-components/button/index.tsx
packages/drip-table/src/components/cell-components/text/index.less
packages/drip-table/src/components/cell-components/text/index.tsx
packages/drip-table/src/components/react-components/button/index.tsx

Text component

---

.dumirc.ts
docs/drip-table/components/index.md
docs/drip-table/components/status.md
packages/drip-table/src/components/cell-components/index.ts
packages/drip-table/src/components/cell-components/status/index.less
packages/drip-table/src/components/cell-components/status/index.tsx

feat: add status component

---

docs/drip-table/components/group.md

chore: update group demo

---

.dumirc.ts
docs/drip-table/props/default-component-lib.md
packages/drip-table/src/layouts/table/index.tsx
packages/drip-table/src/layouts/table/types.ts
packages/drip-table/src/types/index.ts
packages/drip-table/src/utils/ajv.ts

feat: add defaultComponentLib prop

---

packages/drip-table-generator/package.json
packages/drip-table/package.json
packages/drip-table/src/components/cell-components/button/index.tsx
packages/drip-table/src/components/cell-components/hooks.ts
packages/drip-table/src/components/cell-components/popover/index.tsx
packages/drip-table/src/hooks.ts
packages/drip-table/src/index.ts
packages/drip-table/src/utils/hooks.ts
packages/drip-table/src/wrapper/index.tsx

Component context

---

packages/drip-table/src/layouts/table/components/header-cell/index.less
packages/drip-table/src/layouts/table/components/header-cell/index.tsx
packages/drip-table/src/layouts/table/index.tsx

feat: add sort column background

---

packages/drip-table/src/layouts/table/components/header-cell/index.less
packages/drip-table/src/styles/theme/default.less

feat: add css var for sorted column background

---

.dumirc.ts
docs/drip-table/components/checkbox.md
docs/drip-table/components/index.md
packages/drip-table-generator/src/table-components/checkbox.ts
packages/drip-table-generator/src/table-components/index.ts
packages/drip-table/src/components/cell-components/checkbox/index.tsx
packages/drip-table/src/components/cell-components/index.ts

feat: checkbox

---

packages/drip-table-generator/src/table-components/configs.ts

feat: change the horizontal alignment to default left alignment

---

packages/drip-table/src/layouts/table/index.tsx

fix: hook schema event raise should consider array type

---

packages/drip-table/package.json

release: drip-table v3.2.1-alpha.4

---

packages/drip-table/src/utils/sandbox.ts

fix: evaluator script may contains comment line

---

packages/drip-table/src/wrapper/index.tsx

Merge 3.2.1 alpha.8

---

packages/drip-table-generator/package.json
packages/drip-table-generator/src/layouts/table-workstation/editable-table/components/cell/common.tsx
packages/drip-table-generator/src/layouts/table-workstation/editable-table/components/cell/index.tsx
packages/drip-table-generator/src/layouts/table-workstation/editable-table/components/table-section/index.tsx

Hotfix table execute

---

packages/drip-table-generator/package.json
packages/drip-table-generator/src/layouts/table-workstation/editable-table/components/components-selector/selector/index.tsx
packages/drip-table/package.json

Feat generator icon config support url
